import {
  frequencyBySectionHeading,
  frequencyByCssVarSegment,
  frequencyByDescriptionKeywords,
} from "./frequency.js";
import type { ColorItemRow, FrequencyEntry, SystemResult } from "./types.js";

const SAMPLE_HEADINGS_TOP_N = 10;
const SAMPLE_ROWS_PER_HEADING = 5;
const FREQ_TABLE_TOP_N = 40;

function tableRow(cells: string[]): string {
  return "| " + cells.join(" | ") + " |";
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function renderFrequencyTable(
  title: string,
  caption: string,
  entries: FrequencyEntry[],
): string {
  const lines: string[] = [];
  lines.push(`## ${title}`);
  if (caption) lines.push(`_${caption}_`);
  lines.push("");
  if (entries.length === 0) {
    lines.push("(no entries)");
    return lines.join("\n");
  }
  lines.push(tableRow(["key", "count", "systems_present", "example_systems"]));
  lines.push(tableRow(["---", "---:", "---:", "---"]));
  for (const e of entries.slice(0, FREQ_TABLE_TOP_N)) {
    const examples = e.systems.slice(0, 5).join(", ") + (e.systems.length > 5 ? ", ..." : "");
    lines.push(tableRow([escapeCell(e.key), String(e.count), String(e.systems.length), escapeCell(examples)]));
  }
  if (entries.length > FREQ_TABLE_TOP_N) {
    lines.push("");
    lines.push(`_…${entries.length - FREQ_TABLE_TOP_N} more keys truncated. See CSV for full data._`);
  }
  return lines.join("\n");
}

function renderSamples(rows: ColorItemRow[], headingFreq: FrequencyEntry[]): string {
  const lines: string[] = [];
  lines.push("## Sample Rows by Section Heading");
  lines.push(`_Top ${SAMPLE_HEADINGS_TOP_N} headings; up to ${SAMPLE_ROWS_PER_HEADING} sample rows each._`);
  lines.push("");
  for (const entry of headingFreq.slice(0, SAMPLE_HEADINGS_TOP_N)) {
    const samples = rows.filter((r) => r.section_heading === entry.key).slice(0, SAMPLE_ROWS_PER_HEADING);
    lines.push(`### ${entry.key} (n=${entry.count}, ${entry.systems.length} systems)`);
    for (const s of samples) {
      const parts: string[] = [];
      parts.push(`**${s.system}**`);
      parts.push(`label="${s.item_label}"`);
      if (s.hex) parts.push(`hex=${s.hex}`);
      if (s.css_var) parts.push(`css_var=${s.css_var}`);
      if (s.token_ref) parts.push(`token_ref=${s.token_ref}`);
      if (s.description_first_keywords.length > 0) parts.push(`keywords=[${s.description_first_keywords.join(", ")}]`);
      lines.push(`- ${parts.join(" · ")}`);
      if (s.description) {
        const trimmed = s.description.length > 140 ? s.description.slice(0, 140) + "…" : s.description;
        lines.push(`  > ${trimmed.replace(/\n/g, " ")}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function renderRawReport(results: SystemResult[]): string {
  const allRows = results.flatMap((r) => r.rows);
  const totalSystems = results.length;
  const withSection = results.filter((r) => r.has_color_section).length;
  const missing = results.filter((r) => !r.has_color_section).map((r) => r.system);
  const empty = results.filter((r) => r.has_color_section && r.rows.length === 0).map((r) => r.system);

  const headingFreq = frequencyBySectionHeading(allRows);
  const cssVarFreq = frequencyByCssVarSegment(allRows);
  const descFreq = frequencyByDescriptionKeywords(allRows);

  const cssVarRows = allRows.filter((r) => r.css_var !== null).length;
  const descRows = allRows.filter((r) => r.description_first_keywords.length > 0).length;

  const lines: string[] = [];
  lines.push("# Color Roles — Raw Frequency (Pass 1)");
  lines.push("");
  lines.push("_Generated by `pnpm color-roles --pass=raw`. Do not edit by hand — re-run instead._");
  lines.push("");
  lines.push("## Coverage");
  lines.push(`- ${totalSystems} systems scanned`);
  lines.push(`- ${withSection} have a color section, ${missing.length} missing: ${missing.length > 0 ? missing.join(", ") : "(none)"}`);
  if (empty.length > 0) {
    lines.push(`- ${empty.length} have a color section but no extractable bullet rows: ${empty.join(", ")}`);
  }
  lines.push(`- ${allRows.length} total bullet rows extracted`);
  lines.push(`- ${cssVarRows} rows have a CSS variable (${pct(cssVarRows, allRows.length)})`);
  lines.push(`- ${descRows} rows have description keywords (${pct(descRows, allRows.length)})`);
  lines.push("");
  lines.push(renderFrequencyTable(
    "Frequency Axis A — Section Headings",
    "Raw `### Heading` text under the color section, no normalization.",
    headingFreq,
  ));
  lines.push("");
  lines.push(renderFrequencyTable(
    "Frequency Axis B — CSS Var Last Segments",
    `Last 1–2 hyphen-segments of CSS variable names. Only counts rows with a CSS variable (${cssVarRows}/${allRows.length}).`,
    cssVarFreq,
  ));
  lines.push("");
  lines.push(renderFrequencyTable(
    "Frequency Axis C — Description First Keywords",
    "First 1–3 non-stopword tokens of the bullet's description sentence.",
    descFreq,
  ));
  lines.push("");
  lines.push(renderSamples(allRows, headingFreq));
  return lines.join("\n").trim() + "\n";
}

function pct(n: number, total: number): string {
  if (total === 0) return "0%";
  return `${Math.round((n / total) * 100)}%`;
}

const CSV_COLUMNS = [
  "system",
  "section_heading",
  "item_label",
  "hex",
  "css_var",
  "token_ref",
  "description_first_keywords",
  "description",
] as const;

function csvCell(value: string | null | string[]): string {
  if (value === null) return "";
  const s = Array.isArray(value) ? value.join(" ") : value;
  if (/[",\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function renderRawCsv(results: SystemResult[]): string {
  const lines: string[] = [];
  lines.push(CSV_COLUMNS.join(","));
  for (const result of results) {
    for (const row of result.rows) {
      lines.push(CSV_COLUMNS.map((c) => csvCell(row[c] as string | null | string[])).join(","));
    }
  }
  return lines.join("\n") + "\n";
}
