// src/schema/archetypes.ts

import type { MoodArchetype, ArchetypePreset } from "./types.js";

const FONT_FALLBACK = "system-ui, -apple-system, sans-serif";
const MONO_FALLBACK = "ui-monospace, SFMono-Regular, Consolas, monospace";

export const ARCHETYPES: Record<MoodArchetype, ArchetypePreset> = {
  "precise": {
    mood: "precise",
    label: "Precise",
    description: "Sharp edges, light typography, structured restraint",
    neutralUndertone: "cool",
    shadowIntensity: "subtle",
    fontWeights: { heading: 400, ui: 400, body: 300 },
    headingLetterSpacing: "-0.7px",
    bodyLineHeight: "1.45",
    headingLineHeight: "1.10",
    sectionSpacing: "80px",
    componentSpacing: "16px",
    buttonRadius: "4px",
    cardRadius: "6px",
    inputRadius: "4px",
    pillRadius: "9999px",
    defaultFont: "Inter",
    defaultFontFallback: FONT_FALLBACK,
    monoFont: "JetBrains Mono",
    monoFontFallback: MONO_FALLBACK,
    suggestedFonts: [
      { name: "Inter", fallback: FONT_FALLBACK },
      { name: "Source Sans 3", fallback: FONT_FALLBACK },
      { name: "Instrument Sans", fallback: FONT_FALLBACK },
      { name: "Switzer", fallback: FONT_FALLBACK },
    ],
    atmosphereTemplate: `{{brandName}} operates in the register of precision engineering — every decision deliberate, every pixel justified. Light weight (400 headings, 300 body) is the primary signal: here, restraint communicates confidence rather than boldness. The canvas is cool and calm, with {{primaryHex}} deployed surgically as the single chromatic statement.

{{fontFamily}} at weight 400 with −0.7px letter-spacing on headings achieves the taut, considered tension of infrastructure design. Where other systems shout with weight, this one whispers with exactitude. Sharp corners (4px buttons, 6px cards) signal that nothing here is accidental — every edge is intentional.

Structured spacing — 16px component grid, 80px section intervals — creates a layout that reads like a well-organized data table. The subtle shadow system lifts surfaces just enough to establish hierarchy without drama. {{brandName}} built on this archetype communicates: we have thought about everything so you don't have to.`,
    characteristics: [
      "Light weight (400/300) as the primary confidence signal — precision over boldness",
      "Cool-tinted neutrals: slate and cool gray throughout, never warm",
      "Sharp corners (4px buttons, 6px cards) signaling engineering exactitude",
      "Tight negative letter-spacing (−0.7px) on headings for editorial tension",
      "Dense component spacing (16px) for information-rich, structured layouts",
      "Subtle shadow system: surfaces lift without theatrical depth",
      "{{primaryHex}} deployed surgically — active states, primary CTAs, key data highlights",
      "Compact body line-height (1.45) for a crisp, document-like reading experience",
      "Structural whitespace: 80px section breaks that read as intentional breath",
    ],
    dos: [
      "Use weight 400 for headings and weight 300 for body — restraint is the statement",
      "Apply −0.7px letter-spacing on all display headings for editorial tautness",
      "Maintain cool-tinted neutrals throughout — no warm grays or parchment tones",
      "Keep border-radius conservative: 4px for interactive elements, 6px for cards",
      "Use subtle shadows that lift without drama: rgba(15,23,42,0.08) or lighter",
      "Deploy {{primaryHex}} sparingly — active states, primary CTAs, and data highlights only",
      "Tighten component spacing to 16px for information-dense, structured interfaces",
      "Choose {{fontFamily}} or another optical-size-aware grotesque for precision neutrality",
      "Let the type scale and spatial rhythm carry all hierarchy — no decorative additions",
    ],
    donts: [
      "Don't use bold (600+) headings — light weight is the intentional luxury differentiator",
      "Don't use warm-tinted neutrals or parchment backgrounds",
      "Don't apply generous rounded corners (12px+) — they undermine the precision signal",
      "Don't use warm or high-opacity shadows — keep them cool and almost invisible",
      "Don't over-apply the accent color — restraint signals confidence here",
      "Don't use decorative typefaces or italic display fonts",
      "Don't increase component spacing beyond 20px — density conveys structural competence",
      "Don't add decorative illustrations or gradient overlays",
    ],
  },

  "confident": {
    mood: "confident",
    label: "Confident",
    description: "Bold typography, subtle depth, commanding presence",
    neutralUndertone: "neutral",
    shadowIntensity: "subtle",
    fontWeights: { heading: 700, ui: 500, body: 400 },
    headingLetterSpacing: "-2.0px",
    bodyLineHeight: "1.50",
    headingLineHeight: "1.10",
    sectionSpacing: "80px",
    componentSpacing: "24px",
    buttonRadius: "6px",
    cardRadius: "8px",
    inputRadius: "6px",
    pillRadius: "9999px",
    defaultFont: "Inter",
    defaultFontFallback: FONT_FALLBACK,
    monoFont: "JetBrains Mono",
    monoFontFallback: MONO_FALLBACK,
    suggestedFonts: [
      { name: "Inter", fallback: FONT_FALLBACK },
      { name: "Geist", fallback: FONT_FALLBACK },
      { name: "IBM Plex Sans", fallback: FONT_FALLBACK },
      { name: "Satoshi", fallback: FONT_FALLBACK },
    ],
    atmosphereTemplate: `{{brandName}} makes its presence known through typographic authority. Bold headings at weight 700 with aggressive −2.0px letter-spacing compress display copy into powerful, commanding blocks — the kind of type that stops the eye and demands attention. This is a system that has nothing to prove and everything to say.

{{fontFamily}} carries the weight with authority. The neutral palette — neither warm nor cool — refuses to distract from the typographic statement. Whitespace is not decoration; it is the frame that makes the bold moments land harder by contrast. Eighty-pixel section breaks create the breathing room that lets each statement resonate.

Subtle shadows and restrained rounding (6px buttons, 8px cards) signal modern confidence without theatrical flourish. {{primaryHex}} anchors the single chromatic accent, appearing precisely where action is required. {{brandName}} built on this archetype says: we know exactly what we are doing.`,
    characteristics: [
      "700-weight headings with aggressive −2.0px letter-spacing for commanding display type",
      "Neutral undertone palette: neither warm nor cool, refusing to compete with typography",
      "Tight heading line-height (1.10) stacks display copy like editorial billboard lettering",
      "Restrained rounding (6px buttons, 8px cards) — modern but never soft",
      "Subtle shadow system that suggests depth without drama",
      "500-weight UI elements for assertive navigation and interactive labels",
      "80px section spacing that frames each typographic statement as its own moment",
      "{{primaryHex}} reserved strictly for primary actions and key interactive states",
      "Generous component spacing (24px) that prevents crowding and maintains authority",
    ],
    dos: [
      "Use weight 700 for all display headings — the bold weight is the signature",
      "Apply −2.0px letter-spacing on all headings for compressed, authoritative display",
      "Set heading line-height to 1.10 for tight, billboard-style typographic impact",
      "Use 500-weight for UI labels, nav items, and secondary actions",
      "Choose {{fontFamily}} or another high-quality grotesque with a strong weight range",
      "Maintain 80px section spacing to give each typographic moment room to breathe",
      "Keep border-radius restrained: 6px for buttons/inputs, 8px for cards",
      "Deploy {{primaryHex}} exclusively for primary CTAs and active states",
      "Rely on type scale and whitespace to carry hierarchy — no decorative additions",
    ],
    donts: [
      "Don't use light (300) or regular (400) font weights for headings",
      "Don't use warm or dramatically cool-tinted neutrals — stay neutral gray",
      "Don't apply loose or positive letter-spacing to headings",
      "Don't use dramatic multi-layer shadows — subtle depth is the correct register",
      "Don't crowd section spacing below 64px — authority needs breathing room",
      "Don't mix more than two font weights in a single component",
      "Don't over-apply the accent color — it should appear precisely where action is needed",
      "Don't use decorative illustration or heavy visual ornamentation",
    ],
  },

  "expressive": {
    mood: "expressive",
    label: "Expressive",
    description: "Rich depth, generous rounding, atmospheric presence",
    neutralUndertone: "warm",
    shadowIntensity: "medium",
    fontWeights: { heading: 500, ui: 500, body: 400 },
    headingLetterSpacing: "-1.0px",
    bodyLineHeight: "1.50",
    headingLineHeight: "1.15",
    sectionSpacing: "72px",
    componentSpacing: "24px",
    buttonRadius: "8px",
    cardRadius: "12px",
    inputRadius: "8px",
    pillRadius: "9999px",
    defaultFont: "DM Sans",
    defaultFontFallback: FONT_FALLBACK,
    monoFont: "JetBrains Mono",
    monoFontFallback: MONO_FALLBACK,
    suggestedFonts: [
      { name: "DM Sans", fallback: FONT_FALLBACK },
      { name: "Plus Jakarta Sans", fallback: FONT_FALLBACK },
      { name: "Nunito Sans", fallback: FONT_FALLBACK },
      { name: "Source Sans 3", fallback: FONT_FALLBACK },
    ],
    atmosphereTemplate: `{{brandName}} creates an atmosphere before it communicates a message. Depth is the primary design material: medium shadows give surfaces physical presence, pulling cards and panels off the background into a layered, dimensional space. The warm neutral undertone wraps the interface in a quality that feels considered and intentional.

{{fontFamily}} at weight 500 with −1.0px letter-spacing on headings achieves the balance between confident and approachable — present without overpowering. Generous rounding (8px buttons, 12px cards) softens every interaction without tipping into childishness. The 1.15 heading line-height allows display text to breathe slightly, giving it room to feel expressive rather than compressed.

{{primaryHex}} lands against the warm neutral canvas with particular resonance — the warmth in the background harmonizes with the brand color's undertones. The 72px section spacing creates a comfortable rhythm that feels neither rushed nor empty. {{brandName}} on this archetype communicates: we care about how this feels, not just how it works.`,
    characteristics: [
      "Medium shadow system creating genuine dimensional depth and physical surface presence",
      "Warm neutral undertone: backgrounds tinted slightly warm, never cool blue-gray",
      "Generous rounding (8px buttons, 12px cards) that softens without becoming playful",
      "500-weight headings and UI: confident yet never aggressive or commanding",
      "Negative letter-spacing (−1.0px) giving headings considered, editorial presence",
      "Slightly open heading line-height (1.15) allowing display text room to breathe",
      "72px section spacing creating a comfortable, atmospheric layout rhythm",
      "{{primaryHex}} resonating warmly against the neutral canvas for brand cohesion",
      "Generous component spacing (24px) preventing crowding and allowing depth to read",
    ],
    dos: [
      "Use medium shadows that give surfaces genuine physical presence and lift",
      "Apply warm-tinted neutrals throughout — this is the atmospheric foundation",
      "Set heading weight to 500 for confident presence without aggression",
      "Apply −1.0px letter-spacing on all headings for considered editorial character",
      "Keep border-radius generous but refined: 8px for interactions, 12px for cards",
      "Choose {{fontFamily}} or another humanist sans with rounded, approachable terminals",
      "Maintain 72px section spacing for a comfortable, layered layout rhythm",
      "Use depth and shadow as the primary hierarchy signal alongside type scale",
      "Let {{primaryHex}} harmonize with warm neutral undertones for atmospheric cohesion",
    ],
    donts: [
      "Don't use cool blue-gray neutrals — they destroy the warm atmospheric quality",
      "Don't use whisper-level shadows — surfaces need genuine medium depth to establish presence",
      "Don't apply sharp corners (0–4px) — generous rounding is the signature",
      "Don't use weight 700+ headings — the system is expressive, not aggressive",
      "Don't crowd section spacing below 60px — the atmosphere needs room to breathe",
      "Don't use overly tight body line-height (below 1.45) — the system values readability",
      "Don't strip depth in favor of flat design — shadow is a first-class design element here",
      "Don't use neon or highly saturated accents that clash with the warm palette",
    ],
  },

  "modern": {
    mood: "modern",
    label: "Modern",
    description: "Pill shapes, minimal shadow, contemporary lightness",
    neutralUndertone: "neutral",
    shadowIntensity: "whisper",
    fontWeights: { heading: 400, ui: 500, body: 400 },
    headingLetterSpacing: "-1.1px",
    bodyLineHeight: "1.50",
    headingLineHeight: "1.10",
    sectionSpacing: "80px",
    componentSpacing: "24px",
    buttonRadius: "9999px",
    cardRadius: "16px",
    inputRadius: "8px",
    pillRadius: "9999px",
    defaultFont: "Inter",
    defaultFontFallback: FONT_FALLBACK,
    monoFont: "JetBrains Mono",
    monoFontFallback: MONO_FALLBACK,
    suggestedFonts: [
      { name: "Inter", fallback: FONT_FALLBACK },
      { name: "Geist", fallback: FONT_FALLBACK },
      { name: "Sora", fallback: FONT_FALLBACK },
      { name: "Space Grotesk", fallback: FONT_FALLBACK },
    ],
    atmosphereTemplate: `{{brandName}} defines itself through a single unmistakable signature: pill buttons. Every primary call-to-action is a capsule (9999px radius), creating a rhythm of rounded energy that reads immediately as contemporary. This is the visual language of the current moment in product design — the form that signals you are building something new.

Surfaces are almost entirely flat. Near-zero shadow (whisper intensity) means {{brandName}} lives in a world of clean, light, elevated simplicity. Cards have generous rounding (16px) that echoes the pill button language without competing with it. The near-shadowless aesthetic creates the sensation of a product that exists in light rather than space.

{{fontFamily}} at weight 400 with −1.1px letter-spacing on headings achieves a contemporary lightness — present and readable without leaning into editorial compression. {{primaryHex}} carries particular impact against flat surfaces precisely because there is no shadow depth to compete with it. {{brandName}} on this archetype says: we are where the industry is going next.`,
    characteristics: [
      "Pill-radius (9999px) primary buttons as the defining, unmistakable visual signature",
      "Whisper-level shadow: surfaces are nearly flat, existing in light rather than space",
      "Generous card rounding (16px) echoing the pill language throughout the system",
      "Weight 400 headings with −1.1px letter-spacing for contemporary lightness",
      "Neutral undertone palette: clean, unbiased gray that refuses to tint",
      "500-weight UI elements providing interactive affordance without heaviness",
      "80px section spacing creating the airy, startup-product layout rhythm",
      "{{primaryHex}} landing with maximum impact on flat, shadow-free surfaces",
      "8px input radius aligning with card rounding while remaining distinct from pills",
    ],
    dos: [
      "Use pill radius (9999px) on ALL primary buttons — this is the non-negotiable signature",
      "Apply whisper-level shadows only: rgba(0,0,0,0.04) or lighter on elevated surfaces",
      "Set card radius to 16px to carry the pill language into container elements",
      "Use weight 400 for headings — contemporary lightness over editorial compression",
      "Apply −1.1px letter-spacing on display headings for modern, considered character",
      "Choose {{fontFamily}} or another clean grotesque that reads well at 400 weight",
      "Maintain neutral gray undertones throughout — no warm or cool bias",
      "Keep component spacing generous at 24px to let the flat surfaces breathe",
      "Rely on {{primaryHex}} contrast against flat surfaces as the primary accent signal",
    ],
    donts: [
      "Don't use sharp-cornered (0–4px) buttons — pill radius is the defining feature",
      "Don't use medium or dramatic shadows — flat surfaces are the aesthetic foundation",
      "Don't use warm or cool-tinted neutrals — stay on pure neutral gray",
      "Don't apply weight 700 headings that feel heavy against the light surface treatment",
      "Don't crowd section spacing below 64px — the lightness needs room",
      "Don't use card radius below 12px — generous rounding reinforces the pill language",
      "Don't introduce decorative borders or dividers that break the flat surface aesthetic",
      "Don't mix pill buttons with sharp-cornered inputs — maintain rounding consistency",
    ],
  },
};

export function getArchetype(mood: MoodArchetype): ArchetypePreset {
  return ARCHETYPES[mood];
}
